"""Generate m6502_fake_machine.c from Fake6502: the 6502's instructions this library needs, copied from exact line
ranges of the pinned file, with the CPU's state moved from upstream's globals into the core's own struct (each change
listed below and marked 'CHANGED' in the output).  It refuses to run if the source is not the pinned file or an anchor
line has moved.

    python src/csrc/cpu/extract_6502_machine.py <folder holding fake6502.c, or an EchoTalk checkout>

The pinned source: Fake6502 v1.1 by Mike Chambers (2011, public domain: "if you use it please do give credit"), as
EchoTalk vendors it -- https://github.com/jaybird110127/echotalk at 25ba18f850d9367f6690245b756234fe030c4ace,
third_party/fake6502/fake6502.c (sha256 below; fake6502/PINNED.txt).  EchoTalk is Jayson Smith's (@jaybird110127,
BSD-3-Clause); his copy turns off upstream's NES_CPU default so decimal mode is honoured, the Apple II being a MOS
6502 and not a NES.  What is left out: the globals, reset6502, nmi6502, irq6502, exec6502 and step6502 -- our step
driver in m6502.c replaces them (CONTRACT.md 13).
"""
import hashlib
import os
import sys

SHA256 = "6356d2f4550c2f93645023df3eb8a7a3e22e04f3178a324baac34359e4fbb5de"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "m6502_fake_machine.c")

# (first line, last line, the text that must open the range, what it is); line numbers as sed and grep count them
RANGES = [
    (142, 191, "#define FLAG_CARRY     0x01", "the flag bits and the flag macros"),
    (209, 229, "//a few general functions used by various other functions", "push and pull"),
    (241, 242, "static void (*addrtable[256])();", "the tables' declarations"),
    (245, 867, "//addressing mode functions, calculates effective addresses",
     "the addressing modes, getvalue/putvalue, every instruction, the undocumented ones"),
    (870, 928, "static void (*addrtable[256])() = {", "the addressing-mode, instruction and cycle tables"),
]

# (upstream text, replacement, why, how many times it must match) -- applied to the copied text only
SUBS = [
    ("void push16(uint16_t pushval) {", "static void push16(uint16_t pushval) {   /* CHANGED: static */", "push16", 1),
    ("void push8(uint8_t pushval) {", "static void push8(uint8_t pushval) {   /* CHANGED: static */", "push8", 1),
    ("uint16_t pull16() {", "static uint16_t pull16() {   /* CHANGED: static */", "pull16", 1),
    ("uint8_t pull8() {", "static uint8_t pull8() {   /* CHANGED: static */", "pull8", 1),
    # decimal mode: the arithmetic is upstream's (wrong for the NMOS 6502: it adjusts the old accumulator, then
    # stores the binary sum); counted so a board can prove its firmware never reaches it (CONTRACT.md 13)
    ("    #ifndef NES_CPU\n    if (status & FLAG_DECIMAL) {\n",
     "    #ifndef NES_CPU\n    if (status & FLAG_DECIMAL) {\n        M6502_CUR->decimal++;   /* CHANGED: counted */\n",
     "decimal-mode ADC and SBC counted", 2),
]

PRELUDE = r"""/* m6502_fake_machine.c -- GENERATED by extract_6502_machine.py; do not edit.
 *
 * Fake6502 v1.1, (c) 2011 Mike Chambers (miker00lz@gmail.com): "This source code is released into the public domain,
 * but if you use it please do give credit.  I put a lot of effort into writing this!"  Copied from EchoTalk's copy
 * (Jayson Smith, @jaybird110127; fake6502/PINNED.txt), exact line ranges, every change marked CHANGED.
 *
 * Included by m6502.c, which defines struct m6502 and M6502_CUR before it: build m6502.c, never this file.
 */

/* CHANGED: upstream keeps the CPU in globals (pc, sp, a, x, y, status and its helper variables); here they are the
   current core's, so two cores (two units) run side by side, on different threads too */
#define pc (M6502_CUR->pc)
#define sp (M6502_CUR->sp)
#define a (M6502_CUR->a)
#define x (M6502_CUR->x)
#define y (M6502_CUR->y)
#define status (M6502_CUR->status)
#define oldpc (M6502_CUR->oldpc)
#define ea (M6502_CUR->ea)
#define reladdr (M6502_CUR->reladdr)
#define value (M6502_CUR->value)
#define result (M6502_CUR->result)
#define opcode (M6502_CUR->opcode)
#define penaltyop (M6502_CUR->penaltyop)
#define penaltyaddr (M6502_CUR->penaltyaddr)
/* CHANGED: what an instruction adds to its table cycles (a branch taken, a page crossed, decimal mode) */
#define clockticks6502 (M6502_CUR->extra)
/* CHANGED: upstream's externally supplied read6502/write6502 are the core's bus */
#define read6502(addr) m6502_bus_read(M6502_CUR, (uint16_t)(addr))
#define write6502(addr, val) m6502_bus_write(M6502_CUR, (uint16_t)(addr), (uint8_t)(val))
#define UNDOCUMENTED   /* as upstream: the undocumented opcodes are handled (and counted by m6502.c) */
"""


EPILOGUE = r"""
/* CHANGED (ours): the state macros end here, so the step driver after this file names its fields plainly */
#undef pc
#undef sp
#undef a
#undef x
#undef y
#undef status
#undef oldpc
#undef ea
#undef reladdr
#undef value
#undef result
#undef opcode
#undef penaltyop
#undef penaltyaddr
#undef clockticks6502
#undef read6502
#undef write6502
"""


def source_path(arg):
    for p in (os.path.join(arg, "fake6502.c"), os.path.join(arg, "third_party", "fake6502", "fake6502.c")):
        if os.path.isfile(p):
            return p
    sys.exit("fake6502.c not found under %s" % arg)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = source_path(sys.argv[1])
    raw = open(path, "rb").read()
    if hashlib.sha256(raw).hexdigest() != SHA256:
        sys.exit("%s is not the pinned file (sha256 %s)" % (path, SHA256))
    lines = raw.decode("ascii").replace("\r\n", "\n").split("\n")
    out = [PRELUDE]
    for first, last, anchor, what in RANGES:
        if not lines[first - 1].startswith(anchor):
            sys.exit("line %d does not open with %r" % (first, anchor))
        out.append("\n/* ---- fake6502.c lines %d-%d: %s ---- */\n" % (first, last, what))
        out.append("\n".join(lines[first - 1:last]) + "\n")
    text = "".join(out)
    for old, new, why, count in SUBS:
        n = text.count(old)
        if n != count:
            sys.exit("%s: %r matches %d times, not %d" % (why, old, n, count))
        text = text.replace(old, new)
    text += EPILOGUE
    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT), text.count("\n")))


if __name__ == "__main__":
    main()
